### PR TITLE
v.3.3.0 part 1

### LINKED ISSUE #5: Cross Compilation with CMake
Cmake is designed to build, test and package software.
Add a cmake to streamline the code generation for multiple platforms is an approach

CoolProp developpement shows [how to build static library from it](http://www.coolprop.org/dev/coolprop/wrappers/StaticLibrary/index.html#cmake-integration)

The same approach [can be seen here](https://github.com/CoolProp/ExternalMedia/tree/master/Projects)

Compiled library will be installed in  **Resources/Library** following suggestion https://github.com/modelica/ExternalMedia/issues/4#issuecomment-345747096.

### LINKED ISSUE #7: Add CI system
Even though we might not cover all cases (see https://github.com/modelica/ExternalMedia/issues/4#issuecomment-346040608), a basic CI system should help to improve code quality. I volunteer to start with Travis CI and AppVeyor if there are no objections.

### LINKED ISSUE #8: Managing CoolProp interface dependencies - Tree structure
The goal of ExternalMedia library is to provide a framework for interfacing external codes computing fluid properties to Modelica.Media-compatible component models. 

The dependency will follow the [recommendation stated](https://github.com/modelica/ExternalMedia/issues/4#issuecomment-345740364) by @casella and @adrpo : *Download the sources and build the dependency*

How to integrate CoolProp in ExternalMedia project:

1. As a submodule in git
I don't know how submodule works in git but many blogs seems to say that is a really difficult path to make [it work simply.](https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/) I might be wrong. 
2. git subtree
Alternative to git submodules : [git subtree](https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree)

3. External CMake project (ExternalProject_Add).
This how to explain a simple integration: [External CMake Project](https://www.selectiveintellect.net/blog/2016/7/29/using-cmake-to-add-third-party-libraries-to-your-project-1)

For me, the third solution is easier to maintain and understand.
What do you think ? What do I miss ?

### PR DESCRIPTION
**Pull request by jowr**
This is a major rewrite of the CMake script and some of the sources have also been modified. 

- Adds support for TravisCI and AppVeyor, closes #7 
- Uses CoolProp as an external project, closes #8
- It handles a lot of CMake issues and might also fix #5 
- Includes the Modelica utility headers from v3.2.3

Currently open topics are:

- Include instructions and builds for OMC, see #9 (<- I need help with OMC)
- Update Modelica sources to match new version number
- Remove all build scripts except the CMake files
- Update compilation/installation instructions

### CODE REVIEW

**Comment by jowr** [comment]
You can see the Travis builds here: https://travis-ci.com/github/jowr/ExternalMedia

**Comment by jowr** [comment]
Thank you @casella for spending some time on this, also tagging @ibell to get his attention :-) 

I have a few comments regarding the points you mentioned in https://github.com/CoolProp/ExternalMedia/issues/27 :

1. I am open for major changes regarding the CoolProp integration, but the code is not ready for that. The coolpropsolver in ExternalMedia uses all kinds of internal functions which are not exposed in the DLL.
2. Compiling CoolProp with ExternalMedia is not so hard because (a) we can use continuous integration servers to build all kinds of binaries for us and (b) people running Modelica already have a compiler availbale and all we ask for is to install CMake.
3. The Modelica specification now supports special library locations for different compilers. This allows us to ship binaries for VS2012 through VS2019 side-by-side.

This is by no means an effort to crush your plans. My suggestion here is that we stick to the old way of using compiled binaries for v3.3 or v3.4 and that we talk about major changes in conjunction with the update to v4.0.0 - which probably follows the release of the Modelica Standard Library v4.0.0.

**Comment by bilderbuchi** [comment]
Watch out re: Travis integration, it's probably a good idea to implement CI e.g. in GitHub actions, instead, as Travis for open source has become very unattractive lately.

**Comment by casella** [comment]
> I have a few comments regarding the points you mentioned in [CoolProp/ExternalMedia#27](https://github.com/CoolProp/ExternalMedia/issues/27) :
> 
>     1. I am open for major changes regarding the CoolProp integration, but the code is not ready for that. The coolpropsolver in ExternalMedia uses all kinds of internal functions which are not exposed in the DLL.

Aha. I haven't checked all the details yet.

>     2. Compiling CoolProp with ExternalMedia is not so hard because (a) we can use continuous integration servers to build all kinds of binaries for us and (b) people running Modelica already have a compiler availbale and all we ask for is to install CMake.

The problem is that we have all combinations of OS, tool, 32/64 bit, which makes this quite complicated.

>     3. The Modelica specification now supports special library locations for different compilers. This allows us to ship binaries for VS2012 through VS2019 side-by-side.

If you can help me with that, that would be fine. For me it looks a bit like a nightmare :)

> This is by no means an effort to crush your plans. My suggestion here is that we stick to the old way of using compiled binaries for v3.3 or v3.4 and that we talk about major changes in conjunction with the update to v4.0.0 - which probably follows the release of the Modelica Standard Library v4.0.0.

Sounds good to me. Incidentally, MSL 4.0.0 has been [released ](https://github.com/modelica/ModelicaStandardLibrary/releases)in June 2020 already.

**Review by beutlich — COMMENTED** [review]
>     * Includes the Modelica utility headers from v3.2.3

I'd recommend to use the files from v4.0.0 actually. They are backward-compatible to v3.2.3.

**Comment by jowr** [comment]
OK - I can see that we need a structured discussion of all these topics. I'll open new issues and create different PRs for different topics.

**Pull request closed without merging**
