### PR TITLE
Comments c89

### LINKED ISSUE #81: C99 comments
According to MLS spec C89 should be used:
https://specification.modelica.org/v3.4/Ch12.html#external-function-interface
Modelon Impact uses gcc with -std=c89 and complains about the C99 comments.
I will send a PR to fix it

### PR DESCRIPTION
**Pull request by thorade**
convert externalmedialib.h to C89 comments
only /* comments */ allowed

This fixes #81

### CODE REVIEW

**Comment by thorade** [comment]
@casella and @jowr  
This PR is ready for review, the file does not contain any `//` anymore.

**Comment by thorade** [comment]
It seems comments have to be changed in all header files.

**Comment by thorade** [comment]
Also had to change the comments in Modelica code. Now the error related to comments is gone

**Comment by casella** [comment]
LGTM. Thanks @thorade!

**Comment by thorade** [comment]
Thanks!

**Pull request merged**
