### PR TITLE
v.3.3.0 with CI and documentation

### PR DESCRIPTION
**Pull request by jowr**
- [x] All artifacts are built by GitHub CI machines, the "binaries.zip" contains everything needed for a release (also a manual)
- [x] The documentation is built by doxygen and published as PDF inside the Modelica folder and as HTML on the gh-pages branch
- [x] The new documentation has to be reviewed
- [ ] Compatibility with OpenModelica is work-in-progress

### CODE REVIEW

**Comment by jowr** [comment]
From my side, I am ready to merge this PR. However, a second opinion by @casella and @beutlich would be great to merge with more confidence...

**Comment by casella** [comment]
I updated the version annotations of the library

**Comment by casella** [comment]
No need to use or mention versions of MSL prior to 3.2.3, which is backwards compatible.

**Comment by casella** [comment]
@jowr, I think this PR should now be fine, I'll merge it in the v.3.3.0-dev branch now.

The only thing I am unsure of are the [compilation instructions](https://github.com/jowr/ExternalMedia/blob/v.3.3.0-docs/README_compilation.md), they seem to refer to a situation whereby you had to install CMake and make the binaries on your own PC. In fact I had tried that out one month ago, but failed. Should we update that whole file to reflect the new status with the GitHub CI?

Finally, it seems that @dongkeun-oh managed to get this working in OpenModelica, see PR #27, I guess we should coordinate with him to get v.3.3.0 to run with CoolProp 5, before trying to move to CoolProp 6.

Thanks again for your help and sorry for my sluggish response times.

**Pull request merged**
