### PR TITLE
Removed version number from Modelica code

### LINKED ISSUE #63: Remove the version number from the directory name of the Modelica source code
Remove the version number from the directory name of the Modelica source code directory, because that requires changing all the file names every time a new version is released. We could make without it, or possibly change the build script to copy all the required files on a build directory where the version number is added to the Modelica directory name, if that is not too difficult

### PR DESCRIPTION
**Pull request by jowr**
Removed version number from Modelica code and updated the version information to v3.3.2

Closes #63

### CODE REVIEW

**Review by casella — APPROVED** [review]
Changes to the code LGTM

**Comment by jowr** [comment]
Please note that CI only fails on macOS only. I am not even sure that this is among our target platforms.

**Comment by casella** [comment]
> Please note that CI only fails on macOS only. I am not even sure that this is among our target platforms.

As far as I am personally concerned, it isn't. Our experience with OpenModelica is that keeping MacOS compatibility is very hard, because MacOS changes all the time, often in non-backwards compatible ways, and it requires significant resources to keep up with it.

I would suggest to suspend MacOS support for the time being and make sure we are getting full support with Dymola and OpenModelica under Windows and Linux. That is already a major milestone, and I would really like to finalize it ASAP. Later on, we can try to add even more Modelica tools and operating systems. I'll open two tickets about them, so people can add their request of support for them.

**Comment by fedetftpolimi** [comment]
The dynamiclib branch merged the feature/no_version_number branch, which is likely no longer required.
In the dynamiclib branch I also just made a commit that fixes the CMake install target, it still installed the library in the directory with the version number, creating it in the process. Now libraries are installed in the directory without version number.

**Pull request merged**
